"""
HealthPost — AI-powered Clinical Decision Support
Gradio UI replicating the React frontend.
Run: pip install gradio && python app.py
"""

import gradio as gr
import time

# ── Demo Scenarios ──────────────────────────────────────────────────────────
DEMO_SCENARIOS = {
    "Malaria Case": {
        "symptoms": "High fever (39.2°C) for 3 days, chills, profuse sweating at night, headache, body aches, and loss of appetite. Patient reports mosquito bites last week. No vomiting or diarrhea.",
        "age": "adult, 32 years",
    },
    "Skin Infection": {
        "symptoms": "Red, swollen area on left forearm for 5 days. The area is warm to touch with yellowish discharge. Spreading redness around the wound. Mild fever. Patient reports a small cut that preceded the infection.",
        "age": "adult, 45 years",
    },
    "Child Respiratory": {
        "symptoms": "Persistent cough for 7 days, runny nose, mild fever (37.8°C), fast breathing (50 breaths/minute), and chest indrawing. Child is irritable but feeding. No wheezing heard.",
        "age": "child, 2 years",
    },
    "Pregnancy Checkup": {
        "symptoms": "28 weeks pregnant, mild swelling in ankles (bilateral), occasional headaches, blood pressure 130/85 mmHg at last check. Reports normal fetal movement. No visual disturbances or epigastric pain.",
        "age": "adult, 26 years, pregnant",
    },
}

# ── Mock Diagnostic Report ─────────────────────────────────────────────────
MOCK_REPORT = """## 🏥 MedGemma Visit Summary

---

### 📋 Patient Overview
| Field | Value |
|---|---|
| **Age** | Adult, 32 years |
| **Chief Complaint** | Fever, chills, sweating |
| **Duration** | 3 days |
| **Vitals** | Temp: 39.2°C |

---

### 🔬 Differential Diagnosis

| # | Diagnosis | Confidence | Rationale |
|---|-----------|------------|-----------|
| 1 | **Plasmodium falciparum Malaria** | ⬛⬛⬛⬛⬜ 85% | Classic triad: fever, chills, sweating with mosquito exposure |
| 2 | Dengue Fever | ⬛⬛⬜⬜⬜ 40% | Fever + body aches, but no rash or bleeding |
| 3 | Typhoid Fever | ⬛⬜⬜⬜⬜ 20% | Prolonged fever possible, but pattern less typical |

---

### 💊 Recommended Treatment Plan

**First-line Treatment:**
- Artemether-Lumefantrine (AL) — 4 tablets BID × 3 days
- Paracetamol 500mg PRN for fever (max 4g/day)
- ORS for hydration

**Monitoring:**
- Re-check RDT on Day 3
- Monitor temperature every 6 hours
- Watch for danger signs: convulsions, severe vomiting, jaundice

---

### ⚠️ Drug Interaction Check
> ✅ **No significant interactions detected** between Artemether-Lumefantrine and Paracetamol.

---

### 🚨 Referral Assessment

| Criteria | Status |
|----------|--------|
| Danger signs present | ✅ None detected |
| Able to take oral meds | ✅ Yes |
| Pregnancy | ✅ Not applicable |
| **Referral needed** | **🟢 Not required — manage at community level** |

---

> ⚕️ *This report was generated by MedGemma and is intended to support, not replace, clinical decision-making.*
"""

# ── Chat Responses ──────────────────────────────────────────────────────────
CHAT_RESPONSES = {
    "pregnant": "Great question! If the patient is pregnant, **Artemether-Lumefantrine is safe in the 2nd and 3rd trimester** but should be avoided in the 1st trimester. In early pregnancy, consider **oral quinine + clindamycin** as an alternative. Always confirm gestational age before prescribing.",
    "dosage": "**Artemether-Lumefantrine dosing** (adult >35kg): 4 tablets (80/480mg) taken at 0, 8, 24, 36, 48, and 60 hours — total 6 doses over 3 days. Take with fatty food to improve absorption.",
    "referral": "**Refer immediately if any of these danger signs appear:**\n- Unable to drink or breastfeed\n- Persistent vomiting\n- Convulsions\n- Lethargy / unconsciousness\n- Severe anemia (pale palms)\n- Respiratory distress",
    "default": "I can help with questions about this case. Try asking about:\n- Drug dosage adjustments\n- What if the patient is pregnant?\n- When should I refer this patient?\n- Alternative treatments",
}


# ── Handlers ────────────────────────────────────────────────────────────────
def load_demo(scenario_name):
    if scenario_name and scenario_name in DEMO_SCENARIOS:
        s = DEMO_SCENARIOS[scenario_name]
        return s["symptoms"], s["age"]
    return "", ""


def run_workflow(symptoms, age, image, image_type, medications):
    if not symptoms and not age:
        return "⚠️ Please enter symptoms or patient age before running."
    time.sleep(1.5)  # simulate processing
    return MOCK_REPORT


def chat_respond(message, history):
    if not message.strip():
        return "", history
    lower = message.lower()
    if "pregnant" in lower:
        response = CHAT_RESPONSES["pregnant"]
    elif "dos" in lower or "dosage" in lower:
        response = CHAT_RESPONSES["dosage"]
    elif "refer" in lower:
        response = CHAT_RESPONSES["referral"]
    else:
        response = CHAT_RESPONSES["default"]
    history = history + [[message, response]]
    return "", history


# ── Theme ───────────────────────────────────────────────────────────────────
theme = gr.themes.Soft(
    primary_hue=gr.themes.colors.teal,
    secondary_hue=gr.themes.colors.cyan,
    neutral_hue=gr.themes.colors.slate,
    font=gr.themes.GoogleFont("Inter"),
    font_mono=gr.themes.GoogleFont("JetBrains Mono"),
).set(
    button_primary_background_fill="linear-gradient(135deg, *primary_500, *secondary_500)",
    button_primary_text_color="white",
    block_title_text_weight="600",
    block_border_width="1px",
    block_shadow="0 1px 3px 0 rgb(0 0 0 / 0.1)",
)

# ── UI ──────────────────────────────────────────────────────────────────────
with gr.Blocks(theme=theme, title="HealthPost — AI Clinical Decision Support") as demo:

    # Header
    gr.Markdown(
        """
        <div style="text-align:center; padding: 1.5rem 0;">
            <h1 style="margin:0;">🏥 HealthPost</h1>
            <p style="opacity:0.7; margin:0.25rem 0 0.5rem;">
                AI-powered clinical decision support — diagnosis, treatment &amp; drug safety
            </p>
            <span style="background:rgba(0,128,128,0.1); padding:4px 12px; border-radius:20px; font-size:0.85rem;">
                ✨ Powered by MedGemma
            </span>
            &nbsp;
            <span style="background:rgba(0,128,128,0.1); padding:4px 12px; border-radius:20px; font-size:0.85rem;">
                🛡️ MedGemma Impact Challenge 2025
            </span>
        </div>
        """
    )

    with gr.Tabs():
        # ─── Clinical Workspace Tab ────────────────────────────────────
        with gr.Tab("🩺 Clinical Workspace"):

            # Demo loader
            with gr.Group():
                demo_select = gr.Dropdown(
                    choices=list(DEMO_SCENARIOS.keys()),
                    label="🧪 Load a demo scenario (optional)",
                    interactive=True,
                )

            # Patient intake
            with gr.Group():
                gr.Markdown("### 📋 Patient Information")
                symptoms_box = gr.Textbox(
                    label="Symptoms",
                    placeholder="Describe the patient's symptoms in detail...",
                    lines=4,
                )
                with gr.Row():
                    age_box = gr.Textbox(
                        label="Patient Age",
                        placeholder="e.g., adult, child 5 years",
                    )
                    audio_input = gr.Audio(
                        label="Or record symptoms (MedASR)",
                        sources=["microphone"],
                        type="filepath",
                    )

            # Optional attachments
            with gr.Row():
                with gr.Accordion("📷 Add Medical Image (optional)", open=False):
                    image_input = gr.Image(label="Upload a medical photo", type="filepath")
                    image_type = gr.Radio(
                        choices=["Skin/Rash", "Wound", "Eyes", "Other"],
                        value="Skin/Rash",
                        label="Image Type",
                    )
                with gr.Accordion("💊 Current Medications (optional)", open=False):
                    meds_image = gr.Image(label="Upload photo of medications", type="filepath")
                    meds_text = gr.Textbox(
                        label="Or type medication names",
                        placeholder="One per line",
                        lines=3,
                    )

            # Run button
            run_btn = gr.Button(
                "▶️  Run Complete Workflow",
                variant="primary",
                size="lg",
            )

            # Diagnostic output
            report_output = gr.Markdown(label="Diagnostic Report")

            # Follow-up chat
            gr.Markdown("### 💬 Follow-up Questions")
            gr.Markdown(
                "_Ask questions about the diagnosis, dosage, referral criteria, etc._"
            )
            chatbot = gr.Chatbot(height=300)
            with gr.Row():
                chat_input = gr.Textbox(
                    placeholder="e.g., What if the patient is pregnant?",
                    show_label=False,
                    scale=9,
                )
                send_btn = gr.Button("Send", scale=1, variant="primary")

        # ─── Architecture & About Tab ──────────────────────────────────
        with gr.Tab("ℹ️ Architecture & About"):
            gr.Markdown(
                """
## 🏗️ System Architecture

HealthPost orchestrates **five specialised clinical AI modules** into one seamless workflow:

| Step | Module | Purpose |
|------|--------|---------|
| 1 | **MedASR** | Voice → structured symptom text |
| 2 | **MedGemma Vision** | Analyse medical images (skin, wounds, eyes) |
| 3 | **MedGemma Text** | Differential diagnosis + treatment plan |
| 4 | **DDInter API** | Drug-drug interaction safety check |
| 5 | **Referral Engine** | Rule-based escalation guidance |

---

### 🎯 Why HealthPost?

- **One-click workflow** — all modules run automatically in sequence
- **Offline-ready** — designed for low-connectivity health posts
- **CHW-friendly** — plain-language output, no medical jargon
- **Safety-first** — drug interactions checked before any prescription

---

### ⚠️ Important Disclaimer

> This tool is a **decision-support system** for Community Health Workers.
> It does **not** replace professional medical judgment.
> All AI-generated recommendations should be reviewed by a qualified clinician.

---

*Built with ❤️ for the MedGemma Impact Challenge 2025*
                """
            )

    # ── Wiring ──────────────────────────────────────────────────────────
    demo_select.change(load_demo, inputs=demo_select, outputs=[symptoms_box, age_box])

    run_btn.click(
        run_workflow,
        inputs=[symptoms_box, age_box, image_input, image_type, meds_text],
        outputs=report_output,
    )

    send_btn.click(chat_respond, inputs=[chat_input, chatbot], outputs=[chat_input, chatbot])
    chat_input.submit(chat_respond, inputs=[chat_input, chatbot], outputs=[chat_input, chatbot])

    # Footer
    gr.Markdown(
        """
        <div style="text-align:center; padding:1rem 0; opacity:0.6; font-size:0.85rem;">
            <strong>HealthPost</strong> — Supporting CHWs to deliver better care &nbsp;|&nbsp;
            Built with ❤️ for the MedGemma Impact Challenge 2025
        </div>
        """
    )

if __name__ == "__main__":
    demo.launch()
