export const DEMO_SCENARIOS: Record<string, { symptoms: string; age: string }> = {
  "Malaria Case": {
    symptoms: "High fever (39.2°C) for 3 days, chills, profuse sweating at night, headache, body aches, and loss of appetite. Patient reports mosquito bites last week. No vomiting or diarrhea.",
    age: "adult, 32 years",
  },
  "Skin Infection": {
    symptoms: "Red, swollen area on left forearm for 5 days. The area is warm to touch with yellowish discharge. Spreading redness around the wound. Mild fever. Patient reports a small cut that preceded the infection.",
    age: "adult, 45 years",
  },
  "Child Respiratory": {
    symptoms: "Persistent cough for 7 days, runny nose, mild fever (37.8°C), fast breathing (50 breaths/minute), and chest indrawing. Child is irritable but feeding. No wheezing heard.",
    age: "child, 2 years",
  },
  "Pregnancy Checkup": {
    symptoms: "28 weeks pregnant, mild swelling in ankles (bilateral), occasional headaches, blood pressure 130/85 mmHg at last check. Reports normal fetal movement. No visual disturbances or epigastric pain.",
    age: "adult, 26 years, pregnant",
  },
};

export const MOCK_REPORT = `## 🏥 MedGemma Visit Summary

---

### 📋 Patient Overview
| Field | Value |
|---|---|
| **Age** | Adult, 32 years |
| **Chief Complaint** | Fever, chills, sweating |
| **Duration** | 3 days |
| **Vitals** | Temp: 39.2°C |

---

### 🔬 Differential Diagnosis

| # | Diagnosis | Confidence | Rationale |
|---|-----------|------------|-----------|
| 1 | **Plasmodium falciparum Malaria** | ⬛⬛⬛⬛⬜ 85% | Classic triad: fever, chills, sweating with mosquito exposure |
| 2 | Dengue Fever | ⬛⬛⬜⬜⬜ 40% | Fever + body aches, but no rash or bleeding |
| 3 | Typhoid Fever | ⬛⬜⬜⬜⬜ 20% | Prolonged fever possible, but pattern less typical |

---

### 💊 Recommended Treatment Plan

**First-line Treatment:**
- Artemether-Lumefantrine (AL) — 4 tablets BID × 3 days
- Paracetamol 500mg PRN for fever (max 4g/day)
- ORS for hydration

**Monitoring:**
- Re-check RDT on Day 3
- Monitor temperature every 6 hours
- Watch for danger signs: convulsions, severe vomiting, jaundice

---

### ⚠️ Drug Interaction Check
> ✅ **No significant interactions detected** between Artemether-Lumefantrine and Paracetamol.

---

### 🚨 Referral Assessment

| Criteria | Status |
|----------|--------|
| Danger signs present | ✅ None detected |
| Able to take oral meds | ✅ Yes |
| Pregnancy | ✅ Not applicable |
| **Referral needed** | **🟢 Not required — manage at community level** |

---

> ⚕️ *This report was generated by MedGemma and is intended to support, not replace, clinical decision-making.*
`;

export const CHAT_RESPONSES: Record<string, string> = {
  pregnant: "Great question! If the patient is pregnant, **Artemether-Lumefantrine is safe in the 2nd and 3rd trimester** but should be avoided in the 1st trimester. In early pregnancy, consider **oral quinine + clindamycin** as an alternative. Always confirm gestational age before prescribing.",
  dosage: "**Artemether-Lumefantrine dosing** (adult >35kg): 4 tablets (80/480mg) taken at 0, 8, 24, 36, 48, and 60 hours — total 6 doses over 3 days. Take with fatty food to improve absorption.",
  referral: "**Refer immediately if any of these danger signs appear:**\n- Unable to drink or breastfeed\n- Persistent vomiting\n- Convulsions\n- Lethargy / unconsciousness\n- Severe anemia (pale palms)\n- Respiratory distress",
  default: "I can help with questions about this case. Try asking about:\n- Drug dosage adjustments\n- What if the patient is pregnant?\n- When should I refer this patient?\n- Alternative treatments",
};
